[general]
columns = [ 'run', 'event', 'subrun', 'nu_id', 'image_id', 'id', 'trigger', 'category', 'category_topology', 'category_interaction_mode',
            'true_muon_ke', 'reco_muon_ke', 'true_proton_ke', 'reco_proton_ke', 'true_visible_energy', 'reco_visible_energy',
            'true_muon_pt', 'reco_muon_pt', 'true_proton_pt', 'reco_proton_pt', 'true_muon_polar_angle', 'reco_muon_polar_angle',
            'true_muon_azimuthal_angle', 'reco_muon_azimuthal_angle', 'true_opening_angle', 'reco_opening_angle',
            'true_delta_pT', 'reco_delta_pT', 'true_delta_phiT', 'reco_delta_phiT', 'true_delta_alphaT', 'reco_delta_alphaT',
            'muon_softmax', 'proton_softmax', 'selected_1mu1p', 'selected_1muNp', 'selected_1muX', 'crtpmt_match', 'cryostat']
cv_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_cv.log'

[general.variables]
reco_muon_ke = [25, 0, 2000]
reco_proton_ke = [25, 0, 600]
reco_visible_energy = [25, 0, 3000]
reco_muon_pt = [25, 0, 750]
reco_proton_pt = [25, 0, 750]
reco_muon_polar_angle = [25.0, 0.0, 3.14159]
reco_muon_azimuthal_angle = [25.0, 0.0, 3.14159]
reco_opening_angle = [25.0, 0.0, 3.14159]
reco_delta_pT = [25, 0, 1200]
reco_delta_phiT = [25.0, 0.0, 3.14159]
reco_delta_alphaT = [25.0, 0.0, 3.14159]
muon_softmax = [25, 0, 1]
proton_softmax = [25.0, 0.8, 1.0]

[sys.tpcintnoisep1sigma]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_tpcintnoisep1sigma_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.tpcuntunedsigshape]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_tpcuntunedsigshape_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.tpcind1increasegain]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_tpcind1increasegain_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.tpcind1decreasegain]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_tpcind1decreasegain_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.pmtdecreasedqe]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_pmtdecreasedqe2_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.ellipsoidarecomb]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_ellipsoidalrecomb_rev3.log'
nboots = 1000
nuniverses = 1000

[sys.tpccohnoisep1sigma]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = 'sysfiles/output_tpccohnoisep1sigma_rev3.log'
nboots = 1000
nuniverses = 1000