[variables]
visible_energy = [20, 0, 3000]
interaction_pt = [25, 0, 1500]

[geniesys]
52 = 'GENIEReWeight_ICARUS_v2_multisim_ZExpAVariationResponse'
53 = 'GENIEReWeight_ICARUS_v2_multisim_RPA_CCQE'
54 = 'GENIEReWeight_ICARUS_v2_multisim_CoulombCCQE'
55 = 'GENIEReWeight_ICARUS_v2_multisim_NormCCMEC'
56 = 'GENIEReWeight_ICARUS_v2_multisim_NormNCMEC'
57 = 'GENIEReWeight_ICARUS_v2_multisim_NCELVariationResponse'
58 = 'GENIEReWeight_ICARUS_v2_multisim_CCRESVariationResponse'
59 = 'GENIEReWeight_ICARUS_v2_multisim_NCRESVariationResponse'
60 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC1pi'
61 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpCC2pi'
62 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC1pi'
63 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvpNC2pi'
64 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC1pi'
65 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnCC2pi'
66 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC1pi'
67 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvnNC2pi'
68 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC1pi'
69 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpCC2pi'
70 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC1pi'
71 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarpNC2pi'
72 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC1pi'
73 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnCC2pi'
74 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC1pi'
75 = 'GENIEReWeight_ICARUS_v2_multisim_NonRESBGvbarnNC2pi'
76 = 'GENIEReWeight_ICARUS_v2_multisim_RDecBR1gamma'
77 = 'GENIEReWeight_ICARUS_v2_multisim_RDecBR1eta'
78 = 'GENIEReWeight_ICARUS_v2_multisim_COHVariationResponse'
79 = 'GENIEReWeight_ICARUS_v2_multisim_DISBYVariationResponse'
80 = 'GENIEReWeight_ICARUS_v2_multisim_FSI_pi_VariationResponse'
81 = 'GENIEReWeight_ICARUS_v2_multisim_FSI_N_VariationResponse'

[fluxsys]
115 = 'expskin_Flux'
116 = 'horncurrent_Flux'
117 = 'kminus_Flux'
118 = 'kplus_Flux'
119 = 'kzero_Flux'
120 = 'nucleoninexsec_Flux'
121 = 'nucleonqexsec_Flux'
122 = 'nucleontotxsec_Flux'
123 = 'piminus_Flux'
124 = 'pioninexsec_Flux'
125 = 'pionqexsec_Flux'
126 = 'piontotxsec_Flux'
127 = 'piplus_Flux'