[general]
columns = [ 'run', 'event', 'subrun', 'nu_id', 'image_id', 'id', 'trigger', 'category', 'category_topology', 'category_interaction_mode',
            'true_muon_ke', 'reco_muon_ke', 'true_proton_ke', 'reco_proton_ke', 'true_visible_energy', 'reco_visible_energy',
            'true_muon_pt', 'reco_muon_pt', 'true_proton_pt', 'reco_proton_pt', 'true_muon_polar_angle', 'reco_muon_polar_angle',
            'true_muon_azimuthal_angle', 'reco_muon_azimuthal_angle', 'true_opening_angle', 'reco_opening_angle',
            'true_delta_pT', 'reco_delta_pT', 'true_delta_phiT', 'reco_delta_phiT', 'true_delta_alphaT', 'reco_delta_alphaT',
            'muon_softmax', 'proton_softmax', 'selected_1mu1p', 'selected_1muNp', 'selected_1muX']
cv_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_cv.log'

[general.variables]
reco_muon_ke = [25, 0, 2000]
reco_proton_ke = [25, 0, 600]
reco_visible_energy = [25, 0, 3000]
reco_muon_pt = [25, 0, 750]
reco_proton_pt = [25, 0, 750]
reco_muon_polar_angle = [25.0, 0.0, 3.14159]
reco_muon_azimuthal_angle = [25.0, 0.0, 3.14159]
reco_opening_angle = [25.0, 0.0, 3.14159]
reco_delta_pT = [25, 0, 1200]
reco_delta_phiT = [25.0, 0.0, 3.14159]
reco_delta_alphaT = [25.0, 0.0, 3.14159]
muon_softmax = [25, 0, 1]
proton_softmax = [25.0, 0.8, 1.0]

[sys.statistical]
type = 'stats'
group = ['total',]

[sys.tpcuntunedsigshape]
type = 'detector'
group = ['detector', 'total_nostat', 'total']
sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_tpcuntunedsigshape.log'
nboots = 1000
nuniverses = 1000

#[sys.intnoise]
#type = 'detector'
#group = ['detector', 'total_nostat', 'total']
#sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_intnoise.log'
#nboots = 1000
#nuniverses = 1000

#[sys.cohnoise]
#type = 'detector'
#group = ['detector', 'total_nostat', 'total']
#sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_cohnoise.log'
#nboots = 1000
#nuniverses = 1000

#[sys.recombination]
#type = 'detector'
#group = ['detector', 'total_nostat', 'total']
#sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_recombination.log'
#nboots = 1000
#nuniverses = 1000

#[sys.signal_shape]
#type = 'detector'
#group = ['detector', 'total_nostat', 'total']
#sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_sigshape.log'
#nboots = 1000
#nuniverses = 1000

#[sys.optical]
#type = 'detector'
#group = ['detector', 'total_nostat', 'total']
#sys_log = '/exp/icarus/app/users/mueller/sbn_ml_cafmaker/icarus_numu_ml_selection/output_optical.log'
#nboots = 1000
#nuniverses = 1000