- name: particles
  type: hist1d
  var: [sCountParticles, sCountPrimaries]
  xlabel: Particles
  ylabel: Entries (Norm. Event)
  title: Interaction Multiplicity
  save: plots/count_particles.png
  plot_kwargs:
    histtype: barstacked
- name: lowx
  type: hist2d
  var: sLowX
  xlabel: True Low X-Coordinate [cm]
  ylabel: Reco Low X-Coordinate [cm]
  title: Particle Lowest X-Coordinate
  save: plots/lowx.png
- name: primary
  type: confusion
  var: sPrimary_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion
  entries: [Non-primary, Primary]
  save: plots/primary_confusion.png
- name: pid
  type: confusion
  var: sPID_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: plots/pid_confusion.png
- name: primary_pid
  type: confusion
  var: sPrimaryPID_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  save: plots/primary_pid_confusion.png
- name: primary_neutrino
  type: confusion
  var: sPrimary_Neutrino_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion (Neutrinos)
  entries: [Non-primary, Primary]
  save: plots/primary_neutrino_confusion.png
- name: pid_neutrino
  type: confusion
  var: sPID_Neutrino_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion (Neutrinos)
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: plots/pid_neutrino_confusion.png
- name: primary_pid_neutrino
  type: confusion
  var: sPrimaryPID_Neutrino_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion (Neutrinos)
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  save: plots/primary_pid_neutrino_confusion.png
- name: primary_cosmic
  type: confusion
  var: sPrimary_Cosmic_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion (Cosmics)
  entries: [Non-primary, Primary]
  save: plots/primary_cosmic_confusion.png
- name: pid_cosmic
  type: confusion
  var: sPID_Cosmic_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion (Cosmics)
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: plots/pid_cosmic_confusion.png
- name: primary_pid_cosmic
  type: confusion
  var: sPrimaryPID_Cosmic_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion (Cosmics)
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  save: plots/primary_pid_cosmic_confusion.png
- name: flow_1mu1p_efficiency
  type: flow
  direction: ttp
  pops: [0, 1, 2]
  labels: [1$\mu$1p, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTopCut, AllCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$1p Selection Statistics
  span: [-4,3]
  save: plots/flow_1mu1p_efficiency.png
- name: flow_1mu1p_purity
  type: flow
  direction: ptt
  pops: [0, 1, 2]
  labels: [1$\mu$1p, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTopCut, AllCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$1p Selection Statistics
  span: [-4,3]
  save: plots/flow_1mu1p_purity.png