- name: particles
  type: hist1d
  var: [sCountParticles, sCountPrimaries]
  xlabel: Particles
  ylabel: Entries / 2.5e20 POT
  title: Interaction Multiplicity
  save: count_particles.png
  plot_kwargs:
    histtype: barstacked
- name: muon_overlap
  type: hist1d
  var: [sNonCCOverlap, sCCOverlap]
  labels: [Non- Cathode-Crossing Muons, Cathode-Crossing Muons]
  xlabel: Intersection / Union of Best Match
  ylabel: Entries / 2.5e20 POT
  title: Overlap Fraction
  save: muon_overlap.png
  plot_kwargs:
    histtype: step
- name: energy_1mu1p_bias
  type: hist1d
  var: [sEnergy_1mu1p_signal_bias, sEnergy_1mu1p_othernu_bias]
  labels: ['1$\mu$1p', 'Other $\nu$']
  xlabel: ($E_{reco}$ -  $E_{visible}$) / $E_{visible}$
  ylabel: Entries / 2.5e20 POT
  title: Energy Reconstruction for Selected 1$\mu$1p Candidates
  save: energy_1mu1p_bias.png
  plot_kwargs:
    histtype: barstacked
- name: energy_1muNp_bias
  type: hist1d
  var: [sEnergy_1muNp_signal_bias, sEnergy_1muNp_othernu_bias]
  labels: ['1$\mu$Np', 'Other $\nu$']
  xlabel: ($E_{reco}$ -  $E_{visible}$) / $E_{visible}$
  ylabel: Entries / 2.5e20 POT
  title: Energy Reconstruction for Selected 1$\mu$Np Candidates
  save: energy_1muNp_bias.png
  plot_kwargs:
    histtype: barstacked
- name: nuenergy_1mu1p_bias
  type: hist1d
  var: [sNuEnergy_1mu1p_signal_bias, sNuEnergy_1mu1p_othernu_bias]
  labels: ['1$\mu$1p', 'Other $\nu$']
  xlabel: ($E_{reco}$ -  $E_{\nu}$) / $E_{\nu}$
  ylabel: Entries / 2.5e20 POT
  title: Energy Reconstruction for Selected 1$\mu$1p Candidates
  save: nuenergy_1mu1p_bias.png
  plot_kwargs:
    histtype: barstacked
- name: nuenergy_1muNp_bias
  type: hist1d
  var: [sNuEnergy_1muNp_signal_bias, sNuEnergy_1muNp_othernu_bias]
  labels: ['1$\mu$Np', 'Other $\nu$']
  xlabel: ($E_{reco}$ -  $E_{\nu}$) / $E_{\nu}$
  ylabel: Entries / 2.5e20 POT
  title: Energy Reconstruction for Selected 1$\mu$Np Candidates
  save: nuenergy_1muNp_bias.png
  plot_kwargs:
    histtype: barstacked
- name: reco_energy_1mu1p
  type: hist1d
  var: sVisibleEnergyPTT_Topology_All1mu1pCut
  categories: {0: 1$\mu$1p, 1: 1$\mu$0h, 2: 1$\mu$Np, 3: 1$\mu$1$\pi$1p, 4: Other $\nu_\mu$ CC, 5: $\nu$ NC, 6: Cosmic}
  xlabel: Reconstructed Visible Energy [MeV]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$1p Candidates
  save: reco_energy_1mu1p.png
  show_percentage: yes
  plot_kwargs:
    histtype: barstacked
- name: reco_energy_1muNp
  type: hist1d
  var: sVisibleEnergyPTT_Topology_All1muNpCut
  categories: {0: 1$\mu$1p, 1: 1$\mu$0h, 2: 1$\mu$Np, 3: 1$\mu$1$\pi$1p, 4: Other $\nu_\mu$ CC, 5: $\nu$ NC, 6: Cosmic}
  merge: [[2,0], [1,], [3,], [4,], [5,], [6,]]
  xlabel: Reconstructed Visible Energy [MeV]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$Np Candidates
  save: reco_energy_1muNp.png
  show_percentage: yes
  plot_kwargs:
    histtype: barstacked
- name: reco_energy_interaction_mode_1mu1p
  type: hist1d
  var: sVisibleEnergyPTT_InteractionMode_All1mu1pCut
  categories: {0: $\nu_\mu$ CC QE, 1: $\nu_\mu$ CC Res, 2: $\nu_\mu$ CC MEC, 3: $\nu_\mu$ CC DIS, 4: $\nu_\mu$ CC Coh, 5: $\nu_e$ CC, 6: $\nu$ NC, 7: Cosmic}
  xlabel: Reconstructed Visible Energy [MeV]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$1p Candidates
  save: reco_energy_interaction_mode_1mu1p.png
  show_percentage: yes
  plot_kwargs:
    histtype: barstacked
- name: reco_energy_interaction_mode_1muNp
  type: hist1d
  var: sVisibleEnergyPTT_InteractionMode_All1muNpCut
  categories: {0: $\nu_\mu$ CC QE, 1: $\nu_\mu$ CC Res, 2: $\nu_\mu$ CC MEC, 3: $\nu_\mu$ CC DIS, 4: $\nu_\mu$ CC Coh, 5: $\nu_e$ CC, 6: $\nu$ NC, 7: Cosmic}
  xlabel: Reconstructed Visible Energy [MeV]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$Np Candidates
  save: reco_energy_interaction_mode_1muNp.png
  show_percentage: yes
  plot_kwargs:
    histtype: barstacked
- name: reco_flashtime_1mu1p
  type: hist1d
  var: sFlashTimePTT_Topology_All1mu1pCut
  categories: {0: 1$\mu$1p, 1: 1$\mu$0h, 2: 1$\mu$Np, 3: 1$\mu$1$\pi$1p, 4: Other $\nu_\mu$ CC, 5: $\nu$ NC, 6: Cosmic}
  xlabel: Matched Flash Time [$\mu$s]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$1p Candidates
  save: reco_flashtime_1mu1p.png
  plot_kwargs:
    histtype: barstacked
- name: reco_flashtime_1muNp
  type: hist1d
  var: sFlashTimePTT_Topology_All1muNpCut
  categories: {0: 1$\mu$1p, 1: 1$\mu$0h, 2: 1$\mu$Np, 3: 1$\mu$1$\pi$1p, 4: Other $\nu_\mu$ CC, 5: $\nu$ NC, 6: Cosmic}
  merge: [[2,0], [1,], [3,], [4,], [5,], [6,]]
  xlabel: Matched Flash Time [$\mu$s]
  ylabel: Entries / 2.5e20 POT
  title: Selected 1$\mu$Np Candidates
  save: reco_flashtime_1muNp.png
  plot_kwargs:
    histtype: barstacked
- name: csda_muon
  type: hist2d
  var: sCSDA_muon
  xlabel: True Deposited Energy [MeV]
  ylabel: Reco CSDA Energy [MeV]
  title: Muon CSDA Energy Estimation
  save: csda_muon.png
- name: csda_muon2muon
  type: hist2d
  var: sCSDA_muon2muon
  xlabel: True Deposited Energy [MeV]
  ylabel: Reco CSDA Energy [MeV]
  title: Muon CSDA Energy Estimation
  save: csda_muon2muon.png
- name: csda_muon_bias2d
  type: hist2d
  var: sCSDA_muon_bias2d
  xlabel: True Deposited Energy [MeV]
  ylabel: ($E_{csda}$ -  $E_{dep}$) / $E_{dep}$
  title: Muon CSDA Energy Estimation
  save: csda_muon_bias2d.png
- name: csda_muon_bias
  type: hist1d
  var: [sCSDA_muon_bias,]
  labels: ['muons',]
  xlabel: ($E_{csda}$ -  $E_{dep}$) / $E_{dep}$
  ylabel: Entries / 2.5e20 POT
  title: Energy Reconstruction for Contained Muons
  save: csda_muon_bias.png
  plot_kwargs:
    histtype: barstacked
- name: lowx
  type: hist2d
  var: sLowX
  xlabel: True Low X-Coordinate [cm]
  ylabel: Reco Low X-Coordinate [cm]
  title: Particle Lowest X-Coordinate
  save: lowx.png
- name: primary
  type: confusion
  var: sPrimary_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion
  entries: [Non-primary, Primary]
  save: primary_confusion.png
- name: pid
  type: confusion
  var: sPID_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: pid_confusion.png
- name: primary_pid
  type: confusion
  var: sPrimaryPID_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  figsize: [16,12]
  save: primary_pid_confusion.png
- name: primary_neutrino
  type: confusion
  var: sPrimary_Neutrino_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion (Neutrinos)
  entries: [Non-primary, Primary]
  save: primary_neutrino_confusion.png
- name: pid_neutrino
  type: confusion
  var: sPID_Neutrino_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion (Neutrinos)
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: pid_neutrino_confusion.png
- name: primary_pid_neutrino
  type: confusion
  var: sPrimaryPID_Neutrino_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion (Neutrinos)
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  figsize: [16,12]
  save: primary_pid_neutrino_confusion.png
- name: primary_cosmic
  type: confusion
  var: sPrimary_Cosmic_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion (Cosmics)
  entries: [Non-primary, Primary]
  save: primary_cosmic_confusion.png
- name: pid_cosmic
  type: confusion
  var: sPID_Cosmic_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion (Cosmics)
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: pid_cosmic_confusion.png
- name: primary_pid_cosmic
  type: confusion
  var: sPrimaryPID_Cosmic_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion (Cosmics)
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  figsize: [16,12]
  save: primary_pid_cosmic_confusion.png
- name: primary_wellreco
  type: confusion
  var: sPrimaryWellReco_confusion
  xlabel: True Particle Category
  ylabel: Reconstructed Particle Category
  clabel: Primary Efficiency
  title: Particle Primary/Non-primary Confusion
  entries: [Non-primary, Primary]
  save: primary_wellreco_confusion.png
- name: pid_wellreco
  type: confusion
  var: sPIDWellReco_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: pid_wellreco_confusion.png
- name: pid_neutrino_wellreco
  type: confusion
  var: sPIDWellReco_Neutrino_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: PID Efficiency
  title: Particle PID Confusion
  entries: [Photon, Electron, Muon, Pion, Proton]
  save: pid_neutrino_wellreco_confusion.png
- name: primary_pid_wellreco
  type: confusion
  var: sPrimaryPIDWellReco_confusion
  xlabel: True Particle Type
  ylabel: Reconstructed Particle Type
  clabel: Efficiency
  title: Particle Primary+PID Confusion
  entries: [sPhoton,sElectron,sMuon,sPion,sProton,pPhoton,pElectron,pMuon,pPion,pProton]
  figsize: [16,12]
  save: primary_pid_wellreco_confusion.png
- name: flow_1mu1p_efficiency
  type: flow
  direction: ttp
  pops: [[0,1], [2,3,4], 5]
  labels: [1$\mu$1p, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTop1mu1pCut, All1mu1pCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$1p Selection Statistics
  xlabel: Interactions / 2.5e20 POT
  span: [1,9]
  save: flow_1mu1p_efficiency.png
- name: flow_1mu1p_purity
  type: flow
  direction: ptt
  pops: [[0,1], [2,3,4], 5]
  labels: [1$\mu$1p, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTop1mu1pCut, All1mu1pCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$1p Selection Statistics
  xlabel: Interactions / 2.5e20 POT
  span: [1,9]
  save: flow_1mu1p_purity.png
- name: flow_1muNp_efficiency
  type: flow
  direction: ttp
  pops: [[0,1,2,3], 4, 5]
  labels: [1$\mu$Np, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTop1muNpCut, All1muNpCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$Np Selection Statistics
  xlabel: Interactions / 2.5e20 POT
  span: [1,9]
  save: flow_1muNp_efficiency.png
- name: flow_1muNp_purity
  type: flow
  direction: ptt
  pops: [[0,1,2,3], 4, 5]
  labels: [1$\mu$Np, Other $\nu$, Cosmic]
  cuts: [NoCut, FVCut, FVConCut, FVConTop1muNpCut, All1muNpCut]
  clabels: ["No Cut", "Fiducial\nVolume", "Containment", "Topological", "Flash Time"]
  title: 1$\mu$Np Selection Statistics
  xlabel: Interactions / 2.5e20 POT
  span: [1,9]
  save: flow_1mu1Np_purity.png